var TEMPLATE_SIDE_MENU = ''
+'<nav class="header navbar">'
+'    <div class="container-fluid">'
+'        <!-- use .pull-*, couse we need this float on any screen size -->'
+'        <div class="pull-left">'
+''
+'            <button data-sidebar="toggleVisible" class="btn btn-icon navbar-btn">'
+'                <i class="fa fa-bars"></i>'
+''
+'            </button>'
+'            <a class="navbar-brand" href="#" role="logo" aria-label="Logo">'
+'                <img class="logo" src="images/logo/brand-text-dark.png" alt="Brand">'
+'            </a>'
+'        </div>'
+''
+'        <!-- use .pull-*, couse we need this float on any screen size -->'
+'        <div class="pull-right" role="navigation">'
+''
+'            <div class="dropdown-ext">'
+'                <button class="btn btn-link" type="button" id="refreshLoader" data-loading-text="<i class=\'fa fa-refresh fa-spin\'></i>">'
+'                    <i class="fa fa-refresh"></i>'
+'                </button>'
+'                <!-- /.dropdown-menu -->'
+'            </div>'
+'            <!-- /.dropdown -->'
+''
+'            <div class="dropdown">'
+'                <a aria-label="More" class="btn btn-icon navbar-btn dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">'
+'                    <i class="fa fa-ellipsis-v"></i>'
+'                </a>'
+'                <ul class="dropdown-menu dropdown-menu-right" role="menu" style="opacity: 0; display: none; transform: scaleX(1) scaleY(1) translateY(0px); transform-origin: 50% 50% 0px;">'
+'                    <li role="presentation" class="" style="opacity: 1; display: list-item; transform: translateY(0px);"><a role="menuitem" tabindex="-1" href="perfil.html"><span class="pull-right"><i class="fa fa-user text-muted"></i></span>Perfil</a></li>'
+'                    <li role="presentation" class="" style="opacity: 1; display: list-item; transform: translateY(0px);"><a role="menuitem" tabindex="-1" href="perfil.html?sc=visitas"><span class="pull-right"><i class="fa fa-clock-o text-muted"></i></span>Visitas</a></li>'
+'                    <li class="divider" style="opacity: 1; display: list-item; transform: translateY(0px);"></li>'
+'                    <li role="presentation" class="" style="opacity: 1; display: list-item; transform: translateY(0px);"><a role="menuitem" tabindex="-1" href="ayuda.html"><span class="pull-right"><i class="fa fa-question-circle text-muted"></i></span>Ayuda</a></li>'
+'                    <li class="divider" style="opacity: 1; display: list-item; transform: translateY(0px);"></li>'
+''
+'                    <li role="presentation" class="" style="opacity: 1; display: list-item; transform: translateY(0px);"><a role="menuitem" tabindex="-1" onclick="exitSession()" ><span class="pull-right"><i class="fa fa-sign-out text-muted"></i></span>Salir</a></li>'
+'                </ul>'
+'            </div>'
+'            <!-- /.dropdown -->'
+'        </div>'
+'        <!-- /navigation -->'
+'    </div>'
+'    <!-- /.container-fluid -->'
+'</nav>'
+'<!-- /navigation -->'
+''
+'<!-- ============================================'
+'SIDEBAR SECTION'
+'=============================================== -->'
+'<aside class="sidebar" role="complementary">'
+'    <div class="sidebar-block" style="">'
+'        <div class="media">'
+'            <div class="media-left">'
+'                <a href="perfil.html">'
+'                    <img class="media-object img-circle" src="{PROFILE_IMAGE}" alt="photo profile">'
+'                </a>'
+'            </div>'
+'            <div class="media-body">'
+'                <h4 class="media-heading">{FIRST_NAME} {LAST_NAME}</h4>'
+'                <p class="text-muted">'
+'                    <small>{PROFESSIONAL_TITLE}</small>'
+'                </p>'
+'            </div>'
+'        </div>'
+'    </div>'
+'    <!-- /.sidebar-block -->'
+'    <!-- /profile -->'
+''
+'    <!-- /navigation -->'
+'    <div class="nav-wrapper">'
+'        <ul class="nav nav-stacked nav-left nav-tabs nav-contrast-teal" role="navigation">'
+'            <li class="nav-item" role="presentation">'
+'                <a href="perfil.html">'
+'                    <span class="nav-icon"><i class="fa fa-user-md"></i></span>'
+'                    <span class="nav-text">Perfil</span>'
+'                </a>'
+'            </li>'
+'            <li class="divider"></li>'
+'            <li class="nav-header" role="presentation">VISITAS</li>'
+'            <li class="nav-item" role="presentation">'
+'                <a href="pacientes.html">'
+'                    <span class="nav-icon"><i class="fa fa-users"></i></span>'
+'                    <span class="nav-text">Pacientes</span>'
+'                </a>'
+'            </li>'
+'            <li class="divider"></li>'
+'            <li class="nav-header" role="presentation">OTROS</li>'
+'            <li class="nav-item" role="presentation">'
+'                <a href="ayuda.html">'
+'                    <span class="nav-icon"><i class="fa fa-question-circle"></i></span>'
+'                    <span class="nav-text">Ayuda</span>'
+'                </a>'
+'            </li>'
+'            <li class="nav-item" role="presentation">'
+'                <a href="contacto.html">'
+'                    <span class="nav-icon"><i class="fa fa-envelope-o"></i></span>'
+'                    <span class="nav-text">Contacto</span>'
+'                </a>'
+'            </li>'
+'            <li class="nav-item" role="presentation">'
+'                <a href="terminos.html">'
+'                    <span class="nav-icon"><i class="fa fa-pencil-square-o"></i></span>'
+'                    <span class="nav-text">Términos y condiciones </span>'
+'                </a>'
+'            </li>'
+'            <li class="nav-item" role="presentation">'
+'                <a onclick="exitSession();">'
+'                    <span class="nav-icon"><i class="fa fa-sign-in"></i></span>'
+'                    <span class="nav-text">Salir</span>'
+'                </a>'
+'            </li>'
+'        </ul>'
+'    </div>'
+'</aside>'
window.user=JSON.parse(getCookie("user"));
var template_side_menu_props = {
	'{FIRST_NAME}': user.prestador_name,
	'{LAST_NAME}': "",
	'{PROFILE_IMAGE}': "images/img/doctor.svg",
	'{PROFESSIONAL_TITLE}': user.prestador_email
}
document.write(parseTemplate(template_side_menu_props,TEMPLATE_SIDE_MENU));
