var TEMPLATE_SCRIPTS = ''
+'<!-- VENDORS : jQuery & Bootstrap -->'
+'<script src="scripts/vendor.js"></script>'
+'<!-- END VENDORS -->'
+'<!-- DEPENDENCIES : Required plugins -->'
+'<script src="scripts/dependencies.js"></script>'
+'<!-- END DEPENDENCIES -->'
+'<!-- WRAPKIT -->'
+'<script src="scripts/wrapkit.js"></script>'
+'<!-- END WRAPKIT -->'
+'<!-- WRAPKIT SETUPS -->'
+'<script src="scripts/wrapkit-setup.js"></script>'
+'<!-- end WRAPKIT SETUPS -->'
+'<!-- PLUGIN SETUPS: vendors & dependencies setups -->'
+'<script src="scripts/plugin-setups.js"></script>'
+'<!-- END PLUGIN SETUPS -->'
+'<script src="scripts/bootbox.js"></script>'
+'<script src="scripts/toastr.js"></script>'
document.write(TEMPLATE_SCRIPTS);
// Manejos para el refreash!!
